=== yingxiyy/controller/allocate/designerApi/src/main/resources/schema/NE.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/NE",
  "definitions": {
    "NE": {
      "additionalProperties": false,
      "properties": {
        "vendorName": {
          "type": "string"
        },
        "yangModel": {
          "type": "string"
        },
        "productType": {
          "type": "string"
        },
        "nodeType": {
          "type": "string",
          "items": {
            "$ref": "#/definitions/NodeType"
          }
        },
        "cardClass": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CardClass"
          }
        },
        "fixEquipModel": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/FixEquipModel"
          }
        }
      },
      "required": [
        "cardClass",
        "vendorName",
        "fixEquipModel"
      ],
      "title": "NE"
    },
    "FixEquipModel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "equipTypeConfiged": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "chassisClass": {
          "type": "string"
        },
        "tpModel": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TpModel"
          }
        }
      },
      "required": [
        "equipTypeConfiged",
        "name"
      ],
      "title": "FixEquipModel"
    },
    "TpModel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "tpFriendlyName": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "tpInfo": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "tpType": {
          "type": "string"
        }
      },
      "required": [
        "tpFriendlyName",
        "tpInfo",
        "tpType"
      ],
      "title": "TpModel"
    },
    "CardClass": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "card": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Card"
          }
        }
      },
      "title": "CardClass"
    },
    "Card": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "cardType": {
          "type": "string"
        },
        "vendorType": {
          "type": "string"
        },
        "comments": {
          "type": "string"
        },
        "wdmBand": {
          "type": "string"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "possibleSlot": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "ports": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Port"
          }
        },
        "regs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Reg"
          }
        },
        "externalLinks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ExternalLink"
          }
        },
        "internalLinks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/InternalLink"
          }
        },
        "crossConnections": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CrossConnection"
          }
        },
        "externalCrossConnections": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CrossConnection"
          }
        },
        "params": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Param"
          }
        },
        "adminEnable": {
          "type": "boolean",
          "default": true
        }
      },
      "required": [
        "cardType",
        "height",
        "possibleSlot",
        "width"
      ],
      "title": "Card"
    },
    "CrossConnection": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "biDirection": {
          "type": "boolean"
        },
        "initiated": {
          "type": "boolean",
          "default": true
        },
        "additional": {
          "type": "boolean",
          "default": false
        },
        "isFixed": {
          "type": "boolean",
          "default": true
        },
        "existedOnNe": {
          "type": "boolean",
          "default": true
        },
        "multiple": {
          "type": "integer",
          "default": 1
        },
        "description": {
          "type": "string"
        },
        "centralFrequency": {
          "type": "string"
        },
        "from": {
          "$ref": "#/definitions/CrossConnectionPoint"
        },
        "to": {
          "$ref": "#/definitions/CrossConnectionPoint"
        },
        "supportedSignal": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SupportedSignal"
          }
        },
        "wssChannel": {
          "$ref": "#/definitions/WssChannel"
        },
        "amplifier": {
          "$ref": "#/definitions/Amplifier"
        },
        "aps": {
          "$ref": "#/definitions/Aps"
        },
        "serviceType": {
          "type": "string"
        },
        "opModes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/OpMode"
          }
        }
      },
      "required": [
        "biDirection",
        "from",
        "to",
        "type"
      ],
      "title": "CrossConnection"
    },
    "Param": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "name"
      ],
      "title": "Param"
    },
    "WssChannel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "voaUpdateModel": {
          "$ref": "#/definitions/voaUpdateModelEnum"
        },
        "sourceToDestVoa": {
          "type": "number",
          "multipleOf": 0.01
        },
        "destToSourceVoa": {
          "type": "number",
          "multipleOf": 0.01
        },
        "lowerFrequency": {
          "type": "string"
        },
        "upperFrequency": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Param"
          }
        }
      },
      "required": [
        "voaUpdateModel"
      ],
      "title": "WssChannel"
    },
    "Amplifier": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "targetGain": {
          "type": "number",
          "multipleOf": 0.01,
          "default": 19.00
        },
        "gainRange": {
          "$ref": "#/definitions/GainRange",
          "default": "LOW_GAIN_RANGE"
        },
        "targetAttenuation": {
          "type": "number",
          "multipleOf": 0.01
        },
        "targetGainTilt": {
          "type": "number",
          "multipleOf": 0.01,
          "default": 0
        },
        "voaRange": {
          "type": "number",
          "multipleOf": 0.01,
          "default": 0
        },
        "autoPowerReduction": {
          "type": "boolean",
          "default": true
        },
        "enable": {
          "type": "boolean",
          "default": true
        },
        "ampMode": {
          "$ref": "#/definitions/AmpMode",
          "default": "CONSTANT_GAIN"
        },
        "params": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Param"
          },
          "default": [
            {
              "name": "ase-injection",
              "value": "NONE"
            },
            {
              "name": "loss-shutdown-hold-off-time",
              "value": "0"
            }
          ]
        }
      },
      "required": [
      ],
      "title": "Amplifier"
    },
    "Aps": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "apsMode": {
          "type": "string",
          "default": "ABSOLUTE"
        },
        "revertive": {
          "type": "boolean",
          "default": false
        },
        "waitToRestoreTime": {
          "type": "integer",
          "default": 1800000
        },
        "holdOffTime": {
          "type": "integer",
          "default": 0
        },
        "params": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Param"
          }
        }
      },
      "required": [
      ],
      "title": "Aps"
    },
    "CrossConnectionPoint": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "port": {
          "type": "string"
        },
        "portFriendlyName": {
          "type": "string"
        },
        "layer": {
          "type": "string"
        },
        "cardType": {
          "type": "string"
        },
        "supportedSignal": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SupportedSignal"
          }
        },
        "transceiverSupportedSignal": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SupportedSignal"
          }
        }
      },
      "required": [
        "port"
      ],
      "title": "CrossConnectionTo"
    },
    "InternalLink": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "biDirection": {
          "type": "boolean"
        },
        "from": {
          "type": "string"
        },
        "to": {
          "type": "string"
        },
        "multiple": {
          "type": "integer"
        }
      },
      "required": [
        "from",
        "to"
      ],
      "title": "InternalLink"
    },
    "ExternalLink": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "biDirection": {
          "type": "boolean"
        },
        "initiated": {
          "type": "boolean",
          "default": true
        },
        "from": {
          "type": "string"
        },
        "to": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ExternalLinkTo"
          }
        },
        "multiple": {
          "type": "integer"
        },
        "supportedSignal": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SupportedSignal"
          }
        },
        "serviceType": {
          "type": "string"
        },
        "mdPort": {
          "type": "string"
        }
      },
      "required": [
        "biDirection",
        "from",
        "to"
      ],
      "title": "ExternalLink"
    },
    "ExternalLinkTo": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "neType": {
          "type": "string"
        },
        "cardType": {
          "type": "string"
        },
        "port": {
          "type": "string"
        }
      },
      "required": [
        "cardType",
        "port"
      ],
      "title": "PurpleTo"
    },
    "Port": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "index": {
          "type": "string"
        },
        "friendlyName": {
          "type": "string"
        },
        "transceiver": {
          "$ref": "#/definitions/Transceiver"
        },
        "centralFrequency": {
          "type": "string"
        },
        "supportedSignal": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SupportedSignal"
          }
        },
        "portType": {
          "type": "string"
        },
        "biDirection": {
          "type": "boolean"
        },
        "isSlave": {
          "type": "boolean",
          "default": false
        },
        "adminEnable": {
          "type": "boolean",
          "default": false
        },
        "params": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Param"
          }
        }
      },
      "required": [
        "name",
        "supportedSignal",
        "portType",
        "biDirection"
      ],
      "title": "Port"
    },
    "Reg": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "serviceType": {
          "type": "string"
        },
        "supportedSignal": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SupportedSignal"
          }
        },
        "ports": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/RegPort"
          }
        }
      },
      "required": [
        "serviceType",
        "supportedSignal"
      ],
      "title": "Reg"
    },
    "Transceiver": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "initiated": {
          "type": "boolean",
          "default": true
        },
        "supportedSignal": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SupportedSignal"
          }
        }
      },
      "required": [
        "name"
      ],
      "title": "Transceiver"
    },
    "SupportedSignal": {
      "type": "string",
      "enum": [
        "OMS",
        "OTS",
        "OCH",
        "100GbE",
        "400GbE",
        "OTU4",
        "OTU4x2",
        "OTU4x3",
        "OTU4x4",
        "OTU4x6",
        "OTU4x8",
        "ETH_100GBASE_FR1_2KM",
        "ETH_100GBASE_CWDM4",
        "ETH_100GBASE_SR10",
        "ETH_100GBASE_SR4",
        "ETH100GBASELR4",
        "ETH_100GBASE_FR4",
        "ETH_100GBASE_FR",
        "ETH_100GBASE_DR",
        "ETH_100GBASE_LR4",
        "ETH_100GBASE_ER4L",
        "ETH_100GBASE_ER4",
        "ETH_10GBASE_CWDM4",
        "ETH_100GBASE_PSM4",
        "ETH_100GBASE_CLR4",
        "ETH_100GBASE_CR4",
        "ETH_200GBASE_FR4",
        "ETH_400GBASE_ZR",
        "ETH_400GBASE_FR4",
        "ETH_400GBASE_LR4",
        "ETH_400GBASE_LR8",
        "ETH_400GBASE_DR4",
        "ETH_400GMSA_PSM4",
        "100GE FlexE",
        "10GbE",
        "OTU2",
        "STM-64",
        "10GE WAN",
        "ETH_10GB-ZR",
        "ETH_10GB-SR",
        "ETH_10GB-LR",
        "XI-64",
        "XL-64",
        "XS-64"
      ],
      "title": "SupportedSignal"
    },
    "NodeType": {
      "type": "string",
      "enum": [
        "OD",
        "TD"
      ],
      "title": "nodeType"
    },
    "voaUpdateModelEnum": {
      "type": "string",
      "enum": [
        "Automatically",
        "Manually"
      ],
      "title": "voaUpdateModelEnum"
    },
    "AmpMode": {
      "type": "string",
      "enum": [
        "CONSTANT_POWER",
        "CONSTANT_GAIN",
        "DYNAMIC_GAIN",
        "ASE_NOISE"
      ],
      "title": "AmpMode"
    },
    "GainRange": {
      "type": "string",
      "enum": [
        "LOW_GAIN_RANGE",
        "MID_GAIN_RANGE",
        "HIGH_GAIN_RANGE",
        "FIXED_GAIN_RANGE"
      ],
      "title": "AmpMode"
    },
    "ServiceType": {
      "type": "string",
      "enum": [
        "MUX_8x100G",
        "MUX_4x100G",
        "MUX_6x100G",
        "MUX_2x400G",
        "MUX_1x400G",
        "TR400G"
      ],
      "title": "serviceType"
    },
    "PortType": {
      "type": "string",
      "enum": [
        "OP-Sig",
        "OP-A",
        "OP-B",
        "OP-C"
      ],
      "title": "PortType"
    },
    "OpMode": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "grid": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "grid",
        "description"
      ],
      "title": "OpMode"
    },
    "RegPort": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "port": {
          "type": "string"
        },
        "friendlyName": {
          "type": "string"
        }
      },
      "required": [
        "port",
        "friendlyName"
      ],
      "title": "OpMode"
    }
  }
}

=== yingxiyy/controller/allocate/designer/src/main/resources/accelink-O2-F-1-ByteDance-OD-card.json
{
  "vendorName": "accelink",
  "productType": "O2-F-1",
  "yangModel": "ByteDance",
  "nodeType": "OD",
  "cardClass": [
    {
      "name": "MUXPANEL",
      "card": [
        {
          "cardType": "MUXPANEL_32C32L",
          "vendorType": "MUXPANEL_32C32L",
          "wdmBand": "C+L",
          "width": 1,
          "height": 1,
          "possibleSlot": [
            50,
            51
          ],
          "ports": [
            {
              "name": "MUX",
              "portType": "MUX-MUX",
              "supportedSignal": [],
              "biDirection": true,
              "index": "0"
            },
            {
              "name": "M?D?,1,64,1",
              "portType": "MUX-Channel",
              "supportedSignal": [
                "OCH"
              ],
              "biDirection": true,
              "index": "?,5,69,1"
            },
            {
              "name": "MPO?,1,4,1",
              "portType": "OPC-MPO",
              "supportedSignal": [
                "OMS"
              ],
              "biDirection": true,
              "adminEnable": true,
              "index": "?,1,4,1"
            },
            {
              "name": "AUX",
              "portType": "Other",
              "supportedSignal": [
                "OMS"
              ],
              "biDirection": true,
              "index": "70"
            }
          ],
          "internalLinks": [
            {
              "biDirection": true,
              "from": "M?D?,1,8,1",
              "to": "MPO1"
            },
            {
              "biDirection": true,
              "from": "M?D?,33,40,1",
              "to": "MPO1"
            },
            {
              "biDirection": true,
              "from": "M?D?,9,16,1",
              "to": "MPO2"
            },
            {
              "biDirection": true,
              "from": "M?D?,41,48,1",
              "to": "MPO2"
            },
            {
              "biDirection": true,
              "from": "M?D?,17,24,1",
              "to": "MPO3"
            },
            {
              "biDirection": true,
              "from": "M?D?,49,56,1",
              "to": "MPO3"
            },
            {
              "biDirection": true,
              "from": "M?D?,25,32,1",
              "to": "MPO4"
            },
            {
              "biDirection": true,
              "from": "M?D?,57,64,1",
              "to": "MPO4"
            }
          ],
          "externalLinks": [
            {
              "biDirection": true,
              "multiple": 3,
              "from": "MPO?,1,3,1",
              "to": [
                {
                  "cardType": "IRA_CL",
                  "port": "MPO?,1,3,1"
                }
              ]
            },
            {
              "initiated": false,
              "biDirection": true,
              "from": "MPO4",
              "multiple": 8,
              "mdPort": "M?D?,25,32,1",
              "to": [
                {
                  "cardType": "IRA_CL",
                  "port": "EXP?,1,8,1"
                }
              ]
            },
            {
              "initiated": false,
              "biDirection": true,
              "from": "MPO4",
              "multiple": 8,
              "mdPort": "M?D?,57,64,1",
              "to": [
                {
                  "cardType": "IRA_CL",
                  "port": "EXP?,1,8,1"
                }
              ]
            }
          ],
          "externalCrossConnections": [
            {
              "initiated": false,
              "isFixed": false,
              "type": "OCH",
              "biDirection": true,
              "multiple": 64,
              "description": "MUXPANEL-1-<slot>-<from>/<central-frequency>",
              "from": {
                "port": "M?D?,1,64,1"
              },
              "to": {
                "cardType": "IRA_CL",
                "port": "LINE"
              },
              "wssChannel": {
                "voaUpdateModel": "Manually",
                "sourceToDestVoa": 3.00,
                "destToSourceVoa": 3.00,
                "lowerFrequency": "<lower-frequency>",
                "upperFrequency": "<upper-frequency>",
                "params": [
                  {
                    "name": "ase-control-mode",
                    "value": "ASE_AUTO"
                  },
                  {
                    "name": "ase-injection-threshold",
                    "value": "-10.00"
                  },
                  {
                    "name": "source-to-dest-power-control-mode",
                    "value": "APC"
                  },
                  {
                    "name": "auto-control-active-threshold-dest",
                    "value": "0.5"
                  },
                  {
                    "name": "auto-control-range",
                    "value": "6"
                  },
                  {
                    "name": "slice-type",
                    "value": "NORMAL"
                  }
                ]
              }
            }
          ]
        }
      ]
    },
    {
      "name": "IRA",
      "card": [
        {
          "cardType": "IRA_CL",
          "vendorType": "IRA_CL",
          "wdmBand": "C+L",
          "width": 4,
          "height": 1,
          "possibleSlot": [
            1,
            5
          ],
          "ports": [
            {
              "name": "MPO?,1,3,1",
              "portType": "WSS-Mesh",
              "supportedSignal": [
                "OMS"
              ],
              "biDirection": true,
              "adminEnable": true,
              "index": "?,3,5,1"
            },
            {
              "name": "LINE",
              "portType": "OA-Line",
              "transceiver": {
                "name": "TRANSCEIVER?OSC",
                "initiated": true
              },
              "supportedSignal": [
                "OTS"
              ],
              "biDirection": true,
              "adminEnable": true,
              "index": "0"
            },
            {
              "name": "SIG",
              "portType": "OA-Sig",
              "transceiver": {
                "name": "TRANSCEIVER?OSC",
                "initiated": true
              },
              "supportedSignal": [
                "OTS"
              ],
              "biDirection": true,
              "adminEnable": true,
              "index": "1"
            },
            {
              "name": "AUX",
              "portType": "Other",
              "supportedSignal": [
                "OMS"
              ],
              "biDirection": true,
              "index": "15"
            },
            {
              "name": "EXP?,1,8,1",
              "portType": "WSS-Mesh",
              "supportedSignal": [
                "OMS"
              ],
              "biDirection": true,
              "index": "?,6,13,1"
            },
            {
              "name": "EXP33",
              "portType": "WSS-Sig",
              "supportedSignal": [
                "OMS"
              ],
              "biDirection": true,
              "adminEnable": true,
              "index": "2"
            },
            {
              "name": "MF",
              "portType": "Other",
              "supportedSignal": [
                "OMS"
              ],
              "biDirection": true,
              "index": "14"
            }
          ],
          "externalLinks": [
            {
              "biDirection": true,
              "multiple": 3,
              "from": "MPO?,1,3,1",
              "to": [
                {
                  "cardType": "MUXPANEL_32C32L",
                  "port": "MPO?,1,3,1"
                }
              ]
            },
            {
              "biDirection": true,
              "from": "LINE",
              "to": [
                {
                  "neType": "OD",
                  "cardType": "IRA_CL",
                  "port": "LINE"
                },
                {
                  "neType": "OD",
                  "cardType": "OLP3_3",
                  "port": "?SIG,1,3,1"
                },
                {
                  "neType": "OD",
                  "cardType": "ILA_CL",
                  "port": "LINE_WEST"
                },
                {
                  "neType": "OD",
                  "cardType": "DGE_CL",
                  "port": "LINE_WEST"
                }
              ]
            },
            {
              "initiated": false,
              "biDirection": true,
              "from": "EXP1",
              "to": [
                {
                  "cardType": "IRA_CL",
                  "port": "EXP1"
                }
              ]
            },
            {
              "initiated": false,
              "biDirection": true,
              "multiple": 8,
              "from": "EXP?,1,8,1",
              "to": [
                {
                  "cardType": "MUXPANEL_32C32L",
                  "port": "MPO4"
                }
              ]
            }
          ],
          "crossConnections": [
            {
              "initiated": true,
              "type": "BA",
              "biDirection": false,
              "description": "AMPLIFIER-1-<slot>-BAC",
              "from": {
                "port": "SIG",
                "layer": "C"
              },
              "to": {
                "port": "LINE",
                "layer": "C"
              },
              "amplifier": {
                "params": [
                  {
                    "name": "ase-injection",
                    "value": "NONE"
                  },
                  {
                    "name": "loss-shutdown-hold-off-time",
                    "value": "0"
                  }
                ]
              }
            },
            {
              "initiated": true,
              "type": "PA",
              "biDirection": false,
